// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyA11hVdCs1D_C3ju-NCGPKSEPWOzU-eZL0',
  //   appId: '1:658147218168:web:a57fd1d29b388adb2da10d',
  //   messagingSenderId: '658147218168',
  //   projectId: 'gymmasterproject-ac78e',
  //   authDomain: 'gymmasterproject-ac78e.firebaseapp.com',
  //   storageBucket: 'gymmasterproject-ac78e.appspot.com',
  //   measurementId: 'G-V8J44PL68W',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4PmBS0lO1zP0DFMrvcObnVN9cggYC-s',
    appId: '1:658147218168:android:74aea6a95b7d0fff2da10d',
    messagingSenderId: '658147218168',
    projectId: 'gymmasterproject-ac78e',
    storageBucket: 'gymmasterproject-ac78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExBVeeX38NPknrxRivqbDdgca2jTCvzk',
    appId: '1:658147218168:ios:aeab3f1a163ea0da2da10d',
    messagingSenderId: '658147218168',
    projectId: 'gymmasterproject-ac78e',
    storageBucket: 'gymmasterproject-ac78e.appspot.com',
    iosBundleId: 'com.example.gymMasterFontend',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAExBVeeX38NPknrxRivqbDdgca2jTCvzk',
  //   appId: '1:658147218168:ios:9a48fb80cc01df6a2da10d',
  //   messagingSenderId: '658147218168',
  //   projectId: 'gymmasterproject-ac78e',
  //   storageBucket: 'gymmasterproject-ac78e.appspot.com',
  //   iosBundleId: 'com.example.gymMasterFontend.RunnerTests',
  // );
}
